/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.comuna_region;
import modelo.persona;

/**
 *
 * @author Eddie
 */
public class BuscarVotante extends javax.swing.JFrame {
        controlador crt = new controlador();

    /**
     * Creates new form BuscarVotante
     */
    public BuscarVotante() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IzqBarra = new javax.swing.JLabel();
        BarraBuscadora = new javax.swing.JTextField();
        DerBarra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComuna = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IzqBarra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IzqBarra.setText("Buscar por Rut");

        BarraBuscadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraBuscadoraActionPerformed(evt);
            }
        });

        DerBarra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DerBarra.setText("Buscar");
        DerBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerBarraActionPerformed(evt);
            }
        });

        tblComuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tblComuna);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IzqBarra)
                        .addGap(18, 18, 18)
                        .addComponent(BarraBuscadora, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DerBarra)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IzqBarra)
                    .addComponent(BarraBuscadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DerBarra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraBuscadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraBuscadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraBuscadoraActionPerformed

    private void DerBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerBarraActionPerformed
        // TODO add your handling code here:
        if(BarraBuscadora.getText().isEmpty()){
            llenarTabla();

        }else{
            String rut = BarraBuscadora.getText();
            BuscarVotante(rut);

        }
    }//GEN-LAST:event_DerBarraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Supervisor sv = new Supervisor();
        sv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarVotante().setVisible(true);
            }
        });
    }
    public void llenarTabla(){
    ArrayList<persona> lista = crt.Sala(1);
    
    DefaultTableModel modelo = new DefaultTableModel();
    this.tblComuna.setModel(modelo);
    modelo.addColumn("Rut");
    modelo.addColumn("Nombre");
    modelo.addColumn("n° Urna");
    modelo.addColumn("n° Sala");
    modelo.addColumn("Nombre Recinto");
    
    Object[] col = new Object[5];
    
    for(persona tmp : lista){
        col[0] = tmp.getRut();
        col[1] = tmp.getNombre_p(); 
        col[2] = tmp.getAppaterno(); 
        col[3] = tmp.getApmaterno();
        col[4] = tmp.getSexo(); 
        modelo.addRow(col);         
    }
    
}
    public void BuscarVotante(String rut){
    ArrayList<persona> lista = crt.Sala_rut(rut,1);
    
    DefaultTableModel modelo = new DefaultTableModel();
    this.tblComuna.setModel(modelo);
    modelo.addColumn("Rut");
    modelo.addColumn("Nombre");
    modelo.addColumn("n° Urna");
    modelo.addColumn("n° Sala");
    modelo.addColumn("Nombre Recinto");
    
    Object[] col = new Object[5];
    
    for(persona tmp : lista){
        col[0] = tmp.getRut();
        col[1] = tmp.getNombre_p(); 
        col[2] = tmp.getAppaterno(); 
        col[3] = tmp.getApmaterno();
        col[4] = tmp.getSexo(); 
        modelo.addRow(col);         
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraBuscadora;
    private javax.swing.JButton DerBarra;
    private javax.swing.JLabel IzqBarra;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComuna;
    // End of variables declaration//GEN-END:variables
}
